# Generated by Django 4.1.3 on 2022-11-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('search_count', models.CharField(max_length=10)),
            ],
        ),
    ]
